### ISSUE TITLE
Problem: Cannot change signing method at runtime

### ISSUE THREAD

**Issue by devashishdxt** [crypto-com/ibc-solo-machine#24]
Currently, the signing method (i.e., the implementation of `Signer` trait) if fixed at compile time. It is not possible to use different signing methods using the same binary (for example, mnemonic for connection handshake and ledger for actual IBC transfers).

**Comment by devashishdxt** [comment]
@tomtau Should we use dynamic libraries implementing `Signer` trait (similar to event hooks) or is it ok to have two different binaries for different signing methods?

**Comment by tomtau** [comment]
maybe better question for @brianatcrypto -- maybe dynamic is better

**Comment by brianatcrypto** [comment]
yea, dynamic will be good. I think the sequence we are looking at is to have solomachine calling vault to sign the message payload. @jimmyyip-crypto
