### ISSUE TITLE
Problem: Cannot sign transactions using ledger

### ISSUE THREAD

**Issue by devashishdxt** [crypto-com/ibc-solo-machine#3]

**Comment by tomtau** [comment]
@devashishdxt not sure if a part of this or in a separate issue -- some "signer" API separation... so one can get the TX payload, send it to some external signer (could be a ledger or something else) and then broadcast/notify the final signed TX

**Comment by devashishdxt** [comment]
> @devashishdxt not sure if a part of this or in a separate issue -- some "signer" API separation... so one can get the TX payload, send it to some external signer (could be a ledger or something else) and then broadcast/notify the final signed TX

Created an issue for this: https://github.com/devashishdxt/ibc-solo-machine/issues/7.
