### ISSUE TITLE
Problem: Missing `Signer` abstraction for signing transactions

### ISSUE THREAD

**Issue by devashishdxt** [crypto-com/ibc-solo-machine#7]
Having a `Signer` abstraction will be beneficial if we want to develop multiple signing strategies, for example, mnemonic, ledger, etc.

**Comment by tomtau** [comment]
tmkms has this "signer" functionality -- https://github.com/iqlusioninc/tmkms/blob/main/README.txsigner.md
it currently doesn't support Ledger, but it can possibly be added
