### ISSUE TITLE
Problem: no mint/burn "event hooks"

### ISSUE THREAD

**Issue by tomtau** [crypto-com/ibc-solo-machine#8]
more of "nice-to-have".
Right now, all the information is kept inside a solo machine.
One can possibly "deduce" things like the current supply or supply change history by scanning transactions on the external networks -- but that may be a bit cumbersome for the solo machine operator... so it may be good to be able to configure "hooks" that would be called on supply changing events which would allow the operator to store this information in a DB of their choice, a spreadsheet or whatever they prefer.

**Comment by devashishdxt** [comment]
@tomtau When you say mint/burn, do you mean minting and burning tokens on solo machine or actual transfer and receive from IBC chain?

**Comment by tomtau** [comment]
@devashishdxt on a high level both

**Comment by tomtau** [comment]
maybe also hooks for key updates?

**Comment by devashishdxt** [comment]
There can be hooks for all the events in https://github.com/crypto-com/ibc-solo-machine/blob/main/solo-machine-core/src/event.rs

I've added `SignerUpdated` event for key updates.

**Comment by devashishdxt** [comment]
I'm thinking of adding an `EventHandler` trait which can be implemented by anyone and registered as a plugin (similar to https://github.com/AndrewGaspar/rust-plugin-example).
