### ISSUE TITLE
Problem: fixed HD path

### ISSUE THREAD

**Issue by tomtau** [crypto-com/ibc-solo-machine#9]
currently fixed as:
```
const HD_PATH: &str = "m/44'/118'/0'/0/0";
```
https://github.com/devashishdxt/ibc-solo-machine/blob/main/solo-machine/src/crypto.rs#L7

one may want to configure it for different networks

**Comment by devashishdxt** [comment]
I'll make it configurable from cli option as well as environment variable.

**Comment by devashishdxt** [comment]
Done in https://github.com/crypto-com/ibc-solo-machine/pull/10.
