### ISSUE TITLE
Problem: channel handshake open ack failed due signature verification error

### ISSUE THREAD

**Issue by mmsqe** [crypto-com/ibc-solo-machine#97]
signature verification failed after the removal of `VerifyClientState` and `VerifyClientConsensusState` in https://github.com/cosmos/ibc-go/pull/7129

**Comment by yihuang** [comment]
The [failed test case](https://github.com/crypto-org-chain/chain-main/actions/runs/11320630765/job/31478475913)

The error message:
```
deliver_tx response contains error code: failed to execute message; message index: 0: channel handshake open ack failed: failed channel state verification for client (06-solomachine-0): signature verification failed
```
